[project]
name = "tina-agent"
version = "0.1.0"
description = "A self-hosted agent for your tasks"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ddgs>=9.14.1",
    "fastapi[standard]>=0.135.3",
    "fastmcp>=3.2.4",
    "langchain>=1.2.13",
    "langchain-mcp-adapters>=0.2.2",
    "langchain-openai>=1.1.12",
    "markdownify>=1.2.2",
    "pymongo>=4.17.0",
    "readabilipy>=0.3.0",
]
